package com.el.webservice.genereateretailorder.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.el.util.PropertiesUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GenerateRetailOrderClassService service = new GenerateRetailOrderClassService();
 * GenerateRetailOrderClass portType = service.getGenerateRetailOrderClassPort();
 * portType.generateRetailOrder(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GenerateRetailOrderClassService", targetNamespace = "http://oracle.e1.bssv.JE147114/", wsdlLocation = "http://192.168.10.51:8013/TL910/GenerateRetailOrderClass?WSDL")
public class GenerateRetailOrderClassService extends Service {

	private final static URL GENERATERETAILORDERCLASSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.el.webservice.genereateretailorder.client.GenerateRetailOrderClassService.class
					.getName());

	static {
		URL url = null;
		String strUrl = "";
		try {
			URL baseUrl;
			baseUrl = com.el.webservice.genereateretailorder.client.GenerateRetailOrderClassService.class
					.getResource(".");
			PropertiesUtil p = new PropertiesUtil("application.properties");
			strUrl = p.getPropertyByKey("WS_GenerateRetailOrderClass");
			/*
			 * url = new URL(baseUrl,
			 * "http://192.168.10.51:8013/TL910/GenerateRetailOrderClass?WSDL");
			 */
			url = new URL(baseUrl, strUrl);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.10.51:8013/TL910/GenerateRetailOrderClass?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		GENERATERETAILORDERCLASSSERVICE_WSDL_LOCATION = url;
	}

	public GenerateRetailOrderClassService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GenerateRetailOrderClassService() {
		super(GENERATERETAILORDERCLASSSERVICE_WSDL_LOCATION, new QName(
				"http://oracle.e1.bssv.JE147114/",
				"GenerateRetailOrderClassService"));
	}

	/**
	 * 
	 * @return returns GenerateRetailOrderClass
	 */
	@WebEndpoint(name = "GenerateRetailOrderClassPort")
	public GenerateRetailOrderClass getGenerateRetailOrderClassPort() {
		return super
				.getPort(new QName("http://oracle.e1.bssv.JE147114/",
						"GenerateRetailOrderClassPort"),
						GenerateRetailOrderClass.class);
	}

}
