package com.el.webservice.memberinformationclass.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MemberInformationClass", targetNamespace = "http://oracle.e1.bssv.JE147106/")
public interface MemberInformationClass {

	/**
	 * 
	 * @param cErrorFlag
	 * @param szMemberCardNumber
	 * @param szAlternateDirectionType
	 * @param szErrorMessage
	 * @param szErrorCode
	 * @throws BusinessServiceException_Exception
	 */
	@WebMethod(operationName = "MemberInforRevision")
	@RequestWrapper(localName = "MemberInforRevision", targetNamespace = "http://oracle.e1.bssv.JE147106/", className = "com.el.webservice.memberinformationclass.client.De147107")
	@ResponseWrapper(localName = "MemberInforRevisionResponse", targetNamespace = "http://oracle.e1.bssv.JE147106/", className = "com.el.webservice.memberinformationclass.client.De147107")
	public void memberInforRevision(
			@WebParam(name = "CErrorFlag", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> cErrorFlag,
			@WebParam(name = "szAlternateDirectionType", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szAlternateDirectionType,
			@WebParam(name = "szErrorCode", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szErrorCode,
			@WebParam(name = "szErrorMessage", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szErrorMessage,
			@WebParam(name = "szMemberCardNumber", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szMemberCardNumber)
			throws BusinessServiceException_Exception;

}
