package com.el.webservice.genereateretailorder.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GenerateRetailOrderClass", targetNamespace = "http://oracle.e1.bssv.JE147114/")
public interface GenerateRetailOrderClass {

	/**
	 * 
	 * @param szStatusMessage
	 * @param szSuccessFLagYNDL01
	 * @param mnSerialNumberUKID
	 * @param mnNumberOfRowsNUR
	 * @throws BusinessServiceException_Exception
	 */
	@WebMethod(operationName = "GenerateRetailOrder")
	@RequestWrapper(localName = "GenerateRetailOrder", targetNamespace = "http://oracle.e1.bssv.JE147114/", className = "com.el.webservice.genereateretailorder.client.De147104")
	@ResponseWrapper(localName = "GenerateRetailOrderResponse", targetNamespace = "http://oracle.e1.bssv.JE147114/", className = "com.el.webservice.genereateretailorder.client.De147104")
	public void generateRetailOrder(
			@WebParam(name = "mnNumberOfRows_NUR", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Integer> mnNumberOfRowsNUR,
			@WebParam(name = "mnSerialNumber_UKID", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Integer> mnSerialNumberUKID,
			@WebParam(name = "szStatusMessage", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szStatusMessage,
			@WebParam(name = "szSuccessFLagYN_DL01", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szSuccessFLagYNDL01)
			throws BusinessServiceException_Exception;

}
