package com.el.webservice.getnextukid.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetNextUniqueID", targetNamespace = "http://oracle.e1.bssv.JE147101/")
public interface GetNextUniqueID {

	/**
	 * 
	 * @param szObjectName
	 * @param mnUniqueKeyID
	 * @throws BusinessServiceException_Exception
	 */
	@WebMethod(operationName = "GetNextUID")
	@RequestWrapper(localName = "GetNextUID", targetNamespace = "http://oracle.e1.bssv.JE147101/", className = "com.el.webservice.getnextukid.client.Dx00022A")
	@ResponseWrapper(localName = "GetNextUIDResponse", targetNamespace = "http://oracle.e1.bssv.JE147101/", className = "com.el.webservice.getnextukid.client.Dx00022A")
	public void getNextUID(
			@WebParam(name = "mnUniqueKeyID", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<Integer> mnUniqueKeyID,
			@WebParam(name = "szObjectName", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szObjectName)
			throws BusinessServiceException_Exception;

}
