package com.el.webservice.getnextukid.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.el.util.PropertiesUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * GetNextUniqueIDService service = new GetNextUniqueIDService();
 * GetNextUniqueID portType = service.getGetNextUniqueIDPort();
 * portType.getNextUID(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "GetNextUniqueIDService", targetNamespace = "http://oracle.e1.bssv.JE147101/", wsdlLocation = "http://192.168.10.51:8013/TL910/GetNextUniqueID?WSDL")
public class GetNextUniqueIDService extends Service {

	private final static URL GETNEXTUNIQUEIDSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.el.webservice.getnextukid.client.GetNextUniqueIDService.class
					.getName());

	static {
		URL url = null;
		String strUrl = "";
		try {
			URL baseUrl;
			PropertiesUtil p = new PropertiesUtil("application.properties");
			strUrl = p.getPropertyByKey("WS_GetNextUniqueID");
			baseUrl = com.el.webservice.getnextukid.client.GetNextUniqueIDService.class
					.getResource(".");
			/*
			 * url = new URL(baseUrl,
			 * "http://192.168.10.51:8013/TL910/GetNextUniqueID?WSDL");
			 */
			url = new URL(baseUrl, strUrl);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: "
					+ strUrl + ", retrying as a local file");
			logger.warning(e.getMessage());
		}
		GETNEXTUNIQUEIDSERVICE_WSDL_LOCATION = url;
	}

	public GetNextUniqueIDService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GetNextUniqueIDService() {
		super(GETNEXTUNIQUEIDSERVICE_WSDL_LOCATION, new QName(
				"http://oracle.e1.bssv.JE147101/", "GetNextUniqueIDService"));
	}

	/**
	 * 
	 * @return returns GetNextUniqueID
	 */
	@WebEndpoint(name = "GetNextUniqueIDPort")
	public GetNextUniqueID getGetNextUniqueIDPort() {
		return super.getPort(new QName("http://oracle.e1.bssv.JE147101/",
				"GetNextUniqueIDPort"), GetNextUniqueID.class);
	}

}
