package com.el.webservice.membermutipleaddressclass.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.el.util.PropertiesUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MemberMutipleAddressClassService service = new MemberMutipleAddressClassService();
 * MemberMutipleAddressClass portType = service.getMemberMutipleAddressClassPort();
 * portType.memberMutipleAddressRevision(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MemberMutipleAddressClassService", targetNamespace = "http://oracle.e1.bssv.JE147107/", wsdlLocation = "http://192.168.10.51:8013/PY910/MemberMutipleAddressClass?WSDL")
public class MemberMutipleAddressClassService extends Service {

	private final static URL MEMBERMUTIPLEADDRESSCLASSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.el.webservice.membermutipleaddressclass.client.MemberMutipleAddressClassService.class
					.getName());

	static {
		URL url = null;
		String strUrl = "";
		try {
			PropertiesUtil p = new PropertiesUtil("application.properties");
			strUrl = p.getPropertyByKey("WS_MemberMutipleAddressClass");
			URL baseUrl;
			baseUrl = com.el.webservice.membermutipleaddressclass.client.MemberMutipleAddressClassService.class
					.getResource(".");
			url = new URL(baseUrl, strUrl);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.10.51:8013/PY910/MemberMutipleAddressClass?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MEMBERMUTIPLEADDRESSCLASSSERVICE_WSDL_LOCATION = url;
	}

	public MemberMutipleAddressClassService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MemberMutipleAddressClassService() {
		super(MEMBERMUTIPLEADDRESSCLASSSERVICE_WSDL_LOCATION, new QName(
				"http://oracle.e1.bssv.JE147107/",
				"MemberMutipleAddressClassService"));
	}

	/**
	 * 
	 * @return returns MemberMutipleAddressClass
	 */
	@WebEndpoint(name = "MemberMutipleAddressClassPort")
	public MemberMutipleAddressClass getMemberMutipleAddressClassPort() {
		return super.getPort(new QName("http://oracle.e1.bssv.JE147107/",
				"MemberMutipleAddressClassPort"),
				MemberMutipleAddressClass.class);
	}

}
