package com.el.webservice.membermutipleaddressclass.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MemberMutipleAddressClass", targetNamespace = "http://oracle.e1.bssv.JE147107/")
public interface MemberMutipleAddressClass {

	/**
	 * 
	 * @param szE58MemberCardNumber
	 * @param cErrorFlag
	 * @param szAlternateDirectionType
	 * @param szErrorMessage
	 * @param szValidateString
	 * @param szErrorCode
	 * @throws BusinessServiceException_Exception
	 */
	@WebMethod(operationName = "MemberMutipleAddressRevision")
	@RequestWrapper(localName = "MemberMutipleAddressRevision", targetNamespace = "http://oracle.e1.bssv.JE147107/", className = "com.el.webservice.membermutipleaddressclass.client.De147108")
	@ResponseWrapper(localName = "MemberMutipleAddressRevisionResponse", targetNamespace = "http://oracle.e1.bssv.JE147107/", className = "com.el.webservice.membermutipleaddressclass.client.De147108")
	public void memberMutipleAddressRevision(
			@WebParam(name = "CErrorFlag", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> cErrorFlag,
			@WebParam(name = "szAlternateDirectionType", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szAlternateDirectionType,
			@WebParam(name = "szE58MemberCardNumber", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szE58MemberCardNumber,
			@WebParam(name = "szErrorCode", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szErrorCode,
			@WebParam(name = "szErrorMessage", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szErrorMessage,
			@WebParam(name = "szValidateString", targetNamespace = "", mode = WebParam.Mode.INOUT) Holder<String> szValidateString)
			throws BusinessServiceException_Exception;

}
